name: lambda-derive
version: 0.1.0
github: "jvanbruegge/lambda-derive"
license: MIT
author: "Jan van Brügge"
maintainer: "jan.van.brugge@futurice.com"
copyright: "2020 Jan van Brügge"

description: Please see the README on GitHub at <https://github.com/jvanbruegge/lambda-derive#readme>

dependencies:
    - base >= 4.7 && < 5
    - aws-lambda-haskell-runtime >= 2.0.1
    - aeson
    - megaparsec
    - parser-combinators
    - text
    - bytestring
    - telegram-api
    - http-client
    - http-client-tls

library:
    source-dirs: src

executables:
    bootstrap:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -threaded
            - -rtsopts
            - -O2
            - -static
            - -with-rtsopts=-N
            - -Wall
        cc-options: -static
        ld-options: -static -pthread
        dependencies:
            - lambda-derive

default-extensions:
    - DeriveAnyClass
    - DeriveGeneric
    - DerivingStrategies
    - DeriveFunctor
    - DuplicateRecordFields
    - NamedFieldPuns
    - OverloadedLists
    - OverloadedStrings
    - TemplateHaskell
    - BlockArguments
    - LambdaCase
